// Short reference notes for the structures people log most often: what a
// muscle does and which nerve supplies it, or what an organ or nerve is for.
// Keyed by atlas id without the _l / _r side suffix.

const INFO: Record<string, string> = {
  // shoulder and arm
  'muscular.clavicular_part_of_deltoid_muscle': 'Front of the deltoid. Flexes and medially rotates the arm. Axillary nerve (C5–C6).',
  'muscular.acromial_part_of_deltoid_muscle': 'Middle of the deltoid. Main abductor of the arm beyond the first 15°. Axillary nerve (C5–C6).',
  'muscular.scapular_spinal_part_of_deltoid_muscle': 'Back of the deltoid. Extends and laterally rotates the arm. Axillary nerve (C5–C6).',
  'muscular.supraspinatus_muscle': 'Rotator cuff. Starts abduction of the arm and holds the humeral head in its socket. Suprascapular nerve (C5–C6).',
  'muscular.infraspinatus_muscle': 'Rotator cuff. Laterally rotates the arm. Suprascapular nerve (C5–C6).',
  'muscular.teres_minor_muscle': 'Rotator cuff. Laterally rotates the arm. Axillary nerve (C5–C6).',
  'muscular.subscapularis_muscle': 'Rotator cuff. Medially rotates the arm. Upper and lower subscapular nerves (C5–C6).',
  'muscular.teres_major_muscle': 'Extends, adducts and medially rotates the arm. Lower subscapular nerve (C5–C6).',
  'muscular.long_head_of_biceps_brachii': 'Flexes the elbow and supinates the forearm; the long head also helps flex the shoulder. Musculocutaneous nerve (C5–C6).',
  'muscular.short_head_of_biceps_brachii': 'Flexes the elbow and supinates the forearm. Musculocutaneous nerve (C5–C6).',
  'muscular.brachialis_muscle': 'The main flexor of the elbow in every forearm position. Musculocutaneous nerve (C5–C6), with a small radial nerve part.',
  'muscular.long_head_of_triceps_brachii': 'Extends the elbow and helps extend and adduct the shoulder. Radial nerve (C6–C8).',
  'muscular.lateral_head_of_triceps_brachii': 'Extends the elbow. Radial nerve (C6–C8).',
  'muscular.medial_head_of_triceps_brachii': 'Extends the elbow. Radial nerve (C6–C8).',
  'muscular.brachioradialis_muscle': 'Flexes the elbow, strongest with the forearm half-turned (hammer grip). Radial nerve (C5–C6).',
  'muscular.extensor_digitorum': 'Extends the fingers and wrist. Posterior interosseous nerve, a branch of the radial nerve (C7–C8).',
  'muscular.extensor_carpi_radialis_brevis': 'Extends and abducts the wrist; often involved in tennis elbow. Radial nerve (C7–C8).',
  'muscular.humero_ulnar_head_of_flexor_digitorum_superficialis': 'Flexes the fingers at the middle joints and helps flex the wrist. Median nerve (C8–T1).',
  // shoulder girdle, neck and back
  'muscular.descending_part_of_trapezius_muscle': 'Upper trapezius. Elevates and upwardly rotates the shoulder blade. Accessory nerve (XI) with C3–C4.',
  'muscular.transverse_part_of_trapezius_muscle': 'Middle trapezius. Pulls the shoulder blades together. Accessory nerve (XI) with C3–C4.',
  'muscular.ascending_part_of_trapezius_muscle': 'Lower trapezius. Depresses and upwardly rotates the shoulder blade. Accessory nerve (XI) with C3–C4.',
  'muscular.levator_scapulae': 'Elevates the shoulder blade and side-bends the neck. Dorsal scapular nerve (C5) and C3–C4.',
  'muscular.rhomboid_major_muscle': 'Retracts and downwardly rotates the shoulder blade. Dorsal scapular nerve (C4–C5).',
  'muscular.rhomboid_minor_muscle': 'Retracts and downwardly rotates the shoulder blade. Dorsal scapular nerve (C4–C5).',
  'muscular.serratus_anterior_muscle': 'Protracts the shoulder blade and holds it against the ribs; weakness causes winging. Long thoracic nerve (C5–C7).',
  'muscular.latissimus_dorsi_muscle': 'Extends, adducts and medially rotates the arm (pull-ups, rowing). Thoracodorsal nerve (C6–C8).',
  'muscular.sternocostal_head_of_pectoralis_major_muscle': 'Adducts and medially rotates the arm and brings a raised arm down. Medial and lateral pectoral nerves (C6–T1).',
  'muscular.clavicular_head_of_pectoralis_major_muscle': 'Flexes, adducts and medially rotates the arm. Lateral pectoral nerve (C5–C7).',
  'muscular.pectoralis_minor_muscle': 'Draws the shoulder blade forward and down; can compress nerves when tight. Medial pectoral nerve (C8–T1).',
  'muscular.sternocleidomastoid_muscle': 'Turns the head to the opposite side; both together flex the neck. Accessory nerve (XI).',
  'muscular.scalenus_anterior_muscle': 'Raises the first rib and side-bends the neck. Anterior rami of C4–C6.',
  'muscular.scalenus_medius_muscle': 'Raises the first rib and side-bends the neck. Anterior rami of C3–C8.',
  'muscular.splenius_capitis_muscle': 'Extends and turns the head to the same side. Posterior rami of the middle cervical nerves.',
  'muscular.longissimus_thoracis_muscle': 'Part of the erector spinae. Extends and side-bends the spine. Posterior rami of spinal nerves.',
  'muscular.iliocostalis_lumborum_muscle': 'Part of the erector spinae. Extends and side-bends the lumbar spine. Posterior rami of spinal nerves.',
  'muscular.quadratus_lumborum_muscle': 'Side-bends the trunk, hitches the hip and steadies the 12th rib in breathing. Anterior rami of T12–L4.',
  // trunk
  'muscular.rectus_abdominis_muscle': 'Flexes the trunk and supports the abdominal wall. Thoraco-abdominal nerves (T7–T11) and subcostal nerve (T12).',
  'muscular.external_abdominal_oblique_muscle': 'Flexes the trunk and turns it to the opposite side. Thoraco-abdominal nerves (T7–T11) and subcostal nerve (T12).',
  'muscular.internal_abdominal_oblique_muscle': 'Flexes the trunk and turns it to the same side. Thoraco-abdominal nerves, iliohypogastric and ilio-inguinal nerves.',
  'muscular.transversus_abdominis_muscle': 'Compresses the abdomen and braces the trunk. Thoraco-abdominal nerves, iliohypogastric and ilio-inguinal nerves.',
  'muscular.diaphragm': 'The main muscle of breathing in. Phrenic nerve (C3–C5).',
  // hip and thigh
  'muscular.psoas_major': 'Flexes the hip; tight after long sitting. Anterior rami of L1–L3.',
  'muscular.iliacus_muscle': 'Flexes the hip together with psoas major. Femoral nerve (L2–L3).',
  'muscular.gluteus_maximus_muscle': 'Extends and laterally rotates the hip (climbing, sprinting, standing up). Inferior gluteal nerve (L5–S2).',
  'muscular.gluteus_medius_muscle': 'Abducts the hip and keeps the pelvis level when standing on one leg. Superior gluteal nerve (L4–S1).',
  'muscular.gluteus_minimus_muscle': 'Abducts and medially rotates the hip; steadies the pelvis. Superior gluteal nerve (L4–S1).',
  'muscular.piriformis_muscle': 'Laterally rotates the hip. The sciatic nerve usually runs just below it. Nerve to piriformis (S1–S2).',
  'muscular.tensor_fasciae_latae': 'Flexes and abducts the hip and tightens the iliotibial tract. Superior gluteal nerve (L4–S1).',
  'muscular.iliotibial_tract': 'A thick band of fascia from the pelvis to the outside of the tibia that steadies the knee. A common site of runners’ lateral knee pain.',
  'muscular.rectus_femoris_muscle': 'Quadriceps. Extends the knee and flexes the hip. Femoral nerve (L2–L4).',
  'muscular.vastus_lateralis_muscle': 'Quadriceps. Extends the knee. Femoral nerve (L2–L4).',
  'muscular.vastus_medialis_muscle': 'Quadriceps. Extends the knee and guides the kneecap. Femoral nerve (L2–L4).',
  'muscular.vastus_intermedius_muscle': 'Quadriceps, under rectus femoris. Extends the knee. Femoral nerve (L2–L4).',
  'muscular.sartorius_muscle': 'Flexes, abducts and laterally rotates the hip and flexes the knee. Femoral nerve (L2–L3).',
  'muscular.adductor_longus': 'Adducts the hip; often involved in groin strains. Obturator nerve (L2–L4).',
  'muscular.adductor_magnus': 'Adducts the hip; its lower part also extends it. Obturator nerve and the tibial part of the sciatic nerve.',
  'muscular.gracilis_muscle': 'Adducts the hip and flexes the knee. Obturator nerve (L2–L3).',
  'muscular.long_head_of_biceps_femoris': 'Hamstring. Flexes the knee and extends the hip. Tibial part of the sciatic nerve (L5–S2).',
  'muscular.short_head_of_biceps_femoris': 'Hamstring. Flexes the knee. Common fibular part of the sciatic nerve (L5–S2).',
  'muscular.semitendinosus_muscle': 'Hamstring. Flexes the knee, extends the hip and medially rotates the leg. Tibial part of the sciatic nerve (L5–S2).',
  'muscular.semimembranosus_muscle': 'Hamstring. Flexes the knee, extends the hip and medially rotates the leg. Tibial part of the sciatic nerve (L5–S2).',
  // leg and foot
  'muscular.medial_head_of_gastrocnemius': 'Calf. Plantarflexes the ankle and helps flex the knee. Tibial nerve (S1–S2).',
  'muscular.lateral_head_of_gastrocnemius': 'Calf. Plantarflexes the ankle and helps flex the knee. Tibial nerve (S1–S2).',
  'muscular.soleus_muscle': 'Deep calf. Plantarflexes the ankle; key for standing and running. Tibial nerve (S1–S2).',
  'muscular.tibialis_anterior_muscle': 'Dorsiflexes and inverts the foot; shin splints often start here. Deep fibular nerve (L4–L5).',
  'muscular.tibialis_posterior_muscle': 'Inverts the foot and supports the arch. Tibial nerve (L4–L5).',
  'muscular.fibularis_longus_muscle': 'Everts the foot and supports the arches. Superficial fibular nerve (L5–S1).',
  'muscular.fibularis_brevis_muscle': 'Everts the foot. Superficial fibular nerve (L5–S1).',
  'muscular.popliteus_muscle': 'Unlocks the straightened knee by rotating it. Tibial nerve (L4–S1).',
  'muscular.plantar_aponeurosis': 'Thick fascia under the sole that supports the arch. Plantar fasciitis affects it near the heel.',
  // head
  'muscular.temporalis_muscle': 'Closes and retracts the jaw. Mandibular nerve (V3).',
  'muscular.superficial_part_of_masseter': 'Closes the jaw; often tight with clenching. Mandibular nerve (V3).',
  'muscular.frontalis_muscle': 'Raises the eyebrows and wrinkles the forehead. Facial nerve (VII).',
  // nerves
  'nervous.white_matter_of_spinal_cord_2': 'Carries signals between the brain and body. It ends around L1–L2, below which the nerve roots form the cauda equina.',
  'nervous.cauda_equina': 'The bundle of lumbar and sacral nerve roots below the end of the spinal cord.',
  'nervous.sciatic_nerve': 'The largest nerve in the body (L4–S3). It supplies the hamstrings and everything below the knee.',
  'nervous.femoral_nerve': 'L2–L4. Supplies the quadriceps and the skin of the front of the thigh.',
  'nervous.tibial_nerve': 'Branch of the sciatic nerve. Supplies the calf and the sole of the foot.',
  'nervous.common_fibular_nerve': 'Branch of the sciatic nerve that wraps around the neck of the fibula, where pressure can cause foot drop.',
  'nervous.median_nerve': 'C6–T1. Supplies most forearm flexors and the thumb muscles; compressed in carpal tunnel syndrome.',
  'nervous.ulnar_nerve': 'C8–T1. Passes behind the elbow (the “funny bone”) and supplies most small hand muscles.',
  'nervous.radial_nerve': 'C5–T1. Supplies the triceps and the wrist and finger extensors.',
  'nervous.axillary_nerve': 'C5–C6. Supplies the deltoid and teres minor and the skin over the shoulder.',
  'nervous.musculocutaneous_nerve': 'C5–C7. Supplies the biceps, brachialis and coracobrachialis.',
  'nervous.intercostal_nerves': 'Run under each rib to supply the chest wall muscles and skin.',
  'nervous.vagus_nerve_x': 'Cranial nerve X. Carries parasympathetic signals to the heart, lungs and gut.',
  'nervous.facial_nerve_vii': 'Cranial nerve VII. Moves the muscles of facial expression.',
  'nervous.trigeminal_nerve_v': 'Cranial nerve V. Sensation of the face and the chewing muscles.',
  'nervous.accessory_nerve_xi': 'Cranial nerve XI. Supplies the sternocleidomastoid and trapezius.',
  'nervous.optic_nerve_ii': 'Cranial nerve II. Carries vision from the eye.',
  // organs
  'cardiovascular.left_ventricle': 'Pumps oxygen-rich blood into the aorta and around the body. It has the thickest wall of the heart.',
  'cardiovascular.right_ventricle': 'Pumps blood into the lungs through the pulmonary trunk.',
  'cardiovascular.left_atrium': 'Receives oxygen-rich blood from the lungs.',
  'cardiovascular.right_atrium': 'Receives blood returning from the body; the heart’s pacemaker (sinoatrial node) sits in its wall.',
  'visceral.liver': 'Processes nutrients, makes bile and proteins, and clears drugs and toxins.',
  'visceral.gallbladder': 'Stores and concentrates bile, released after fatty meals.',
  'visceral.stomach': 'Stores and starts digesting food with acid and enzymes.',
  'visceral.pancreas': 'Makes digestive enzymes and the hormones insulin and glucagon.',
  'lymphoid.spleen': 'Filters the blood and stores immune cells. It sits under the left lower ribs.',
  'visceral.fibrous_capsule_of_kidney': 'The kidney filters the blood, makes urine and helps control blood pressure.',
  'visceral.urinary_bladder': 'Stores urine.',
  'visceral.thyroid_gland': 'Makes the hormones that set the body’s metabolic rate.',
  'visceral.trachea': 'The windpipe, carrying air to the lungs.',
  'visceral.oesophagus': 'Carries food from the throat to the stomach.',
  'visceral.duodenum': 'The first part of the small intestine, where bile and pancreatic juice join the food.',
  'visceral.jejunum': 'Middle part of the small intestine, where most nutrients are absorbed.',
  'visceral.transverse_colon': 'Part of the large intestine, where water is absorbed.',
  'visceral.superior_lobe_of_left_lung': 'Upper lobe of the left lung.',
  'visceral.inferior_lobe_of_left_lung': 'Lower lobe of the left lung.',
  'visceral.superior_lobe_of_right_lung': 'Upper lobe of the right lung.',
  'visceral.middle_lobe_of_right_lung': 'Middle lobe of the right lung.',
  'visceral.inferior_lobe_of_right_lung': 'Lower lobe of the right lung.',
  'approx.cerebral_hemisphere':
    'The source atlas’s cerebral cortex is not openly licensed, so this hemisphere is an approximate shape fitted to the skull. Use it for notes about the head and brain, not for anatomy.',
  // bones
  'skeletal.patella': 'The kneecap, inside the quadriceps tendon. It improves the leverage of the quadriceps.',
  'skeletal.sacrum': 'Five fused vertebrae joining the spine to the pelvis at the sacro-iliac joints.',
  'skeletal.coccyx': 'The tailbone.',
};

/** Reference note for a structure, if one is written. */
export function infoFor(id: string): string | undefined {
  return INFO[id.replace(/_[lr]$/, '')];
}

export const INFO_IDS = Object.keys(INFO);
